# Generated by Django 3.2.7 on 2021-09-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210908_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='overview',
            field=models.CharField(max_length=100),
        ),
    ]
